# Generated by Django 5.2.7 on 2025-10-25 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku_code', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_category', models.CharField(max_length=100)),
                ('product_subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('reorder_quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_rating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True)),
                ('employment_status', models.CharField(blank=True, choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('self_employed', 'Self-Employed'), ('student', 'Student'), ('retired', 'Retired')], max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, choices=[('admin', 'Admin'), ('education', 'Education'), ('sales', 'Sales'), ('service', 'Service'), ('skilled_trades', 'Skilled Trade'), ('tech', 'Tech')], max_length=20, null=True)),
                ('education', models.CharField(blank=True, choices=[('bachelor', 'Bachelor'), ('diploma', 'Diploma'), ('doctorate', 'Doctorate'), ('master', 'Master'), ('secondary', 'Secondary')], max_length=20, null=True)),
                ('household_size', models.IntegerField(blank=True, null=True)),
                ('has_children', models.BooleanField(default=False)),
                ('income_range', models.CharField(blank=True, choices=[('below_25k', '$0 - 25,000'), ('25k-50k', '$25,000 - $50,000'), ('50k-75k', '$50,000 - $75,000'), ('75k-100k', '$75,000 - $100,000'), ('above_100k', '$100,000+')], max_length=20, null=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
