# Generated by Django 5.2.6 on 2025-10-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='education',
            field=models.CharField(blank=True, choices=[('bachelor', 'Bachelor'), ('diploma', 'Diploma'), ('doctorate', 'Doctorate'), ('master', 'Master'), ('secondary', 'Secondary')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='household_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('education', 'Education'), ('sales', 'Sales'), ('service', 'Service'), ('skilled_trades', 'Skilled Trade'), ('tech', 'Tech')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('self_employed', 'Self-Employed'), ('student', 'Student'), ('retired', 'Retired')], max_length=20, null=True),
        ),
    ]
